instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nats
    release: bosh
  - name: postgres-9.4
    release: bosh
  - name: blobstore
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: warden_cpi
    release: bosh-warden-cpi
  - name: garden
    release: garden-linux
  - name: user_add
    properties:
      users:
      - name: jumpbox
        public_key: ((jumpbox_ssh.public_key))
    release: os-conf
  name: bosh
  networks:
  - default:
    - dns
    - gateway
    name: directors
  - name: public
    static_ips:
    - ((external_ip))
  persistent_disk_type: 10GB
  properties:
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
    blobstore:
      address: ((internal_ip))
      agent:
        password: ((blobstore_agent_password))
        user: agent
      director:
        password: ((blobstore_director_password))
        user: director
      port: 25250
      provider: dav
    compiled_package_cache:
      options:
        blobstore_path: /var/vcap/store/tmp/compiled_package_cache
      provider: local
    director:
      address: 127.0.0.1
      cpi_job: warden_cpi
      db:
        adapter: postgres
        database: bosh
        host: 127.0.0.1
        listen_address: 127.0.0.1
        password: ((postgres_password))
        user: postgres
      default_ssh_options:
        gateway_host: ((external_ip))
        gateway_user: jumpbox
      enable_dedicated_status_worker: true
      enable_nats_delivered_templates: true
      enable_post_deploy: true
      events:
        record_events: true
      flush_arp: true
      generate_vm_passwords: true
      ignore_missing_gateway: true
      name: ((director_name))
      ssl:
        cert: ((director_ssl.certificate))
        key: ((director_ssl.private_key))
      user_management:
        local:
          users:
          - name: admin
            password: ((admin_password))
          - name: hm
            password: ((hm_password))
        provider: local
      workers: 4
    garden:
      allow_host_access: true
      debug_listen_address: 127.0.0.1:17013
      default_container_grace_time: 0
      destroy_containers_on_start: true
      disk_quota_enabled: false
      graph_cleanup_threshold_in_mb: 0
      listen_address: 127.0.0.1:7777
      listen_network: tcp
    hm:
      director_account:
        ca_cert: ((director_ssl.ca))
        password: ((hm_password))
        user: hm
      resurrector_enabled: true
    nats:
      address: 127.0.0.1
      password: ((nats_password))
      user: nats
    ntp:
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    postgres:
      adapter: postgres
      database: bosh
      host: 127.0.0.1
      listen_address: 127.0.0.1
      password: ((postgres_password))
      user: postgres
    warden_cpi:
      agent:
        blobstore:
          options:
            endpoint: http://10.254.50.4:25250
            password: ((blobstore_agent_password))
            user: agent
          provider: dav
        mbus: nats://nats:((nats_password))@10.254.50.4:4222
      host_ip: 10.254.50.4
      warden:
        connect_address: 127.0.0.1:7777
        connect_network: tcp
  stemcell: default
  vm_type: default
name: bosh
releases:
- name: bosh
  sha1: 37630c636a030454d55703cfdd495d733525353f
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-263.2.0-ubuntu-trusty-3445.7-20170915-052445-759948783-20170915052451.tgz?versionId=3kjVQuRK7JyrnbKEbKhLRi7qyo0wBXZJ
  version: 263.2.0
- name: bosh-warden-cpi
  sha1: d240afadc718c7f117c0880dbd3801c8e362c5df
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-warden-cpi-35-ubuntu-trusty-3445.7-20170901-172917-396543358-20170901172920.tgz?versionId=MhqRClutBJ38fmDuLUeTVg2EpI6YqRFZ
  version: "35"
- name: garden-linux
  sha1: 979101c727008e2ea3f43856593c70af18e31b0b
  url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/garden-linux-0.342.0-ubuntu-trusty-3445.7-20170901-011312-774022578-20170901011318.tgz?versionId=s5IsHM0DFBW_.tZZkZdk8TLdzXVbBPHp
  version: 0.342.0
- name: os-conf
  sha1: af5a2c9f228b9d7ec4bd051d71fef0e712fa1549
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=12
  version: 12
stemcells:
- alias: default
  os: ubuntu-trusty
  version: "3445.7"
update:
  canaries: 0
  canary_watch_time: 30000-180000
  max_in_flight: 1
  update_watch_time: 30000-180000
properties:
  store_hack:
    bosh_client: admin
    bosh_client_secret: ((admin_password))
    bosh_ca_cert: ((director_ssl.ca))
    bosh_environment: https://((external_ip)):25555
    bosh_gw_user: jumpbox
    bosh_gw_private_key: ((jumpbox_ssh.private_key))
variables:
- name: admin_password
  type: password
- name: blobstore_director_password
  type: password
- name: blobstore_agent_password
  type: password
- name: hm_password
  type: password
- name: nats_password
  type: password
- name: postgres_password
  type: password
- name: default_ca
  options:
    common_name: ca
    is_ca: true
  type: certificate
- name: mbus_bootstrap_ssl
  options:
    alternative_names:
    - ((internal_ip))
    - ((external_ip))
    ca: default_ca
    common_name: ((internal_ip))
  type: certificate
- name: director_ssl
  options:
    alternative_names:
    - ((internal_ip))
    - ((external_ip))
    ca: default_ca
    common_name: ((internal_ip))
  type: certificate
- name: jumpbox_ssh
  type: ssh
