#!/usr/bin/env bash

set -e # bail out early if any command fails
set -u # fail if we hit unset variables
set -o pipefail # fail if any component of any pipe fails

[[ -z "${DEBUG:-""}" ]] || set -x

: "${DIRECTOR_NAME:="chaplin"}"
: "${WORKSPACE:="$HOME/workspace"}"
: "${MANIFESTS:="$WORKSPACE/litehouse-release/manifests"}"

: "${BBL_DIRECTOR:="$WORKSPACE/deployments-london/bosh-bbl-director-$DIRECTOR_NAME"}"
: "${BBL_DIRECTOR_VARS:="$WORKSPACE/deployments-london/bosh-bbl-director-$DIRECTOR_NAME/$DIRECTOR_NAME.cf-rabbitmq.gcp.london.cf-app.com-vars.yml"}"



main() {
  local director_address
  director_address="$(bbl --state-dir "$BBL_DIRECTOR" director-address)"
  director_username="$(bbl --state-dir "$BBL_DIRECTOR" director-username)"
  director_password="$(bbl --state-dir "$BBL_DIRECTOR" director-password)"
  director_ca_cert="$(bbl --state-dir "$BBL_DIRECTOR" director-ca-cert)"

  cf_api_url="https://api.chaplin.cf-rabbitmq.gcp.london.cf-app.com"
  cf_uaa_url="https://uaa.chaplin.cf-rabbitmq.gcp.london.cf-app.com"
  cf_admin_password=$(bosh interpolate --path=/cf_admin_password "$BBL_DIRECTOR_VARS")

  bosh interpolate \
    "$MANIFESTS/litehouse-template.yml" \
    --vars-store "$MANIFESTS/litehouse-vars-store.yml" \
    --var cf-api-url="$cf_api_url" \
    --var cf-uaa-url="$cf_uaa_url" \
    --var cf-admin-username=admin \
    --var cf-admin-password="$cf_admin_password" \
    --var bosh-url="$director_address" \
    --var bosh-root-ca-cert="$director_ca_cert" \
    --var bosh-basic-username="$director_username" \
    --var bosh-basic-password="$director_password"

    # > "$WORKSPACE/litehouse-release/manifest/litehouse-manifest.yml"
}

main
