#!/usr/bin/env bash

set -e # bail out early if any command fails
set -u # fail if we hit unset variables
set -o pipefail # fail if any component of any pipe fails

[[ -z "${DEBUG:-""}" ]] || set -x

: "${WORKSPACE:="$HOME/workspace"}"
: "${MANIFESTS:="$WORKSPACE/litehouse-release/manifests"}"



main() {
    bosh interpolate \
    ~/workspace/bosh-deployment/bosh.yml \
    -o ~/workspace/bosh-deployment/bosh-lite.yml \
    -o ~/workspace/bosh-deployment/jumpbox-user.yml \
    -o ~/workspace/bosh-deployment/external-ip-not-recommended.yml \
    -o ~/workspace/bosh-deployment/misc/bosh-dev.yml \
    --vars-store ./creds.yml \
    -v director_name="Bosh Lite Director" \
    -v internal_ip=127.0.0.1 \
    -v external_ip=104.199.81.49
}

main
