#!/usr/bin/env bash

set -e # bail out early if any command fails
set -u # fail if we hit unset variables
set -o pipefail # fail if any component of any pipe fails

[[ -z "${DEBUG:-""}" ]] || set -x

: "${WORKSPACE:="$HOME/workspace"}"

: "${LITEHOUSE:="$WORKSPACE/litehouse-release"}"
: "${MANIFESTS:="$LITEHOUSE/manifests"}"
: "${BOSH_LITE_TEMPLATE_ASSET:="$LITEHOUSE/src/github.com/vlad-stoian/litehouse/assets/bosh-lite-template.yml"}"

: "${BOSH_DEPLOYMENT:="$WORKSPACE/bosh-deployment"}"



main() {
    bosh interpolate \
    "$BOSH_DEPLOYMENT/bosh.yml" \
    -o "$BOSH_DEPLOYMENT/bosh-lite.yml" \
    -o "$BOSH_DEPLOYMENT/jumpbox-user.yml" \
    -o "$BOSH_DEPLOYMENT/external-ip-not-recommended.yml" \
    -o "$BOSH_DEPLOYMENT/misc/bosh-dev.yml" \
    -o "$MANIFESTS/operations/remove-extra.yml" \
    | tee "$BOSH_LITE_TEMPLATE_ASSET"
}

main
